server:
  port: 9002

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: had1:8848
        namespace: e6ddf427-47fe-4878-85a5-ac028786b3b2
management:
  endpoints:
    web:
      exposure:
        include: '*'
