server:
  port: 9003

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment-route
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**

        - id: payment-route2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/cb/get/**
eureka:
  client:
    # 不向注册中心注册自己
    registerWithEureka: true
    # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetchRegistry: true
    serviceUrl:
      # 设置于eureka server交互的地址查询服务和注册服务都系要依赖这个地址
      defaultZone: http://sc1:7001/eureka/,http://sc2:7002/eureka/
  instance:
    instance-id: cloud-gateway
    prefer-ip-address: true